### ISSUE TITLE
Array element

### ISSUE THREAD

**Issue by epriwahyu** [sivaprakasaman/BME_511_FinalProject#1]
Hi!
Your work is amazing. 
I am interested on how spectral and temporal information are important for CI user, especially in melody. 

I tried to run your code, Main.m
However, I got this error. Would you like to help?
I am still new in programming. 
![Capture](https://user-images.githubusercontent.com/9244675/127629626-8c714375-f6a2-4537-b3d1-bbe843acbe79.png)

Thanks

**Comment by sivaprakasaman** [comment]
Hi, thank you!

I will refer you to the updated version of the code found here:

https://github.com/sivaprakasaman/Timbre_SfN_2021

I think your issue is that `CF_ind` (the index of the CF of the simulated neurons you wish to view) or `compare` (the indices of the instruments in `instruments` to compare) may exceed the number of simulated neurons or instruments. Perhaps changing `CF_ind` to 1 and `compare` to [1,1] or [1,2] depending on how many instruments you are simulating. 

If none of the above works, feel free to download the new code linked above. That one should work and has a couple new ways to visualize the data/corrected calculations.
